---
- name: Os patch servers
  hosts: all
  become: yes
  become_user: root
  gather_facts: no
  pre_task:
    
  - name: Enable all repos
    shell: |
        echo "Hello"

- hosts: all
  become: true
  roles:
    - base
    
