---

- hosts: all
  become: yes
  become_user: root
  gather_facts: no
  pre_tasks:
    - community.general.mail:
        subject: 'OS patching for {{ ansible_hostname }} is beginning now.'
        from: someone@gmail.com
        body: 'Automated OS patching for {{ ansible_hostname }} is beginning now.'
        to: gertbowker@gmail.com
        charset: utf8
      delegate_to: localhost


- hosts: all
  become: true
  roles:
    - base
    - ansible_user
    - dnf
    - samba
    - xorg
    - reboot


    # post_tasks:
    # - mail:
    #     subject: 'OS patching for {{ ansible_hostname }} has completed.'
    #     from: someone@gmail.com
    #     body: "Automated OS patching for {{ ansible_hostname }} has completed."
    #     to: gertbowker@gmail.com
    #     charset: utf8
    #   delegate_to: localhost
