---

- hosts: all
  become: true
  pre_tasks:

  - name: Say hello
    shell: | 
       echo "Hello"
       
- hosts: all
  become: true
  roles:
    - base
    - ansible_user
    - dnf
    - samba
    - reboot
