---

- hosts: all
  become: yes
  become_user: root
  gather_facts: no
  pre_tasks:

  pre_tasks:
    - mail:
        subject: 'OS patching for {{ ansible_hostname }} is beginning now.'
        from: 'svc_cls@{{ ansible_fqdn }}'
        body: 'Automated OS patching for {{ ansible_hostname }} is beginning now.'
        to: '{{ app_email }}'
        charset: utf8
      delegate_to: localhost
      tags: mail
  
- hosts: all
  become: true
  roles:
    - base
#    - ansible_user
    - dnf
    - samba
    - xorg
    - reboot
