---

- hosts: all
  become: yes
  become_user: root
  gather_facts: no
  pre_tasks:

  - name: Say hello
    shell: | 
       echo "Hello"
       
- hosts: all
  become: true
  roles:
    - base
    - ansible_user
    - dnf
    - samba
    - docker-engine
    - reboot
