---

- hosts: all
  become: yes
  become_user: root
  gather_facts: True
  pre_tasks:

- hosts: all
  become: true
  roles:
#    - base
#    - ansible_user
    - selinux
    - dnf
#    - samba
#    - xorg
    - reboot
