---
- name: Report on Oracle Linux servers' last patched dates and create concatenated output file
  hosts: all
  become: true  # Become root to access logs
  gather_facts: true
  tasks:

    - name: Check if the server uses yum (for OL7 and older)
      when: ansible_facts['distribution_major_version'] in ['7']
      stat:
        path: /var/log/yum.log
      register: yum_log_status

    - name: Check if the server uses dnf (for OL8 and newer)
      when: ansible_facts['distribution_major_version'] in ['8']
      stat:
        path: /var/log/dnf.log
      register: dnf_log_status

    - name: Get the last patch date from yum logs (for OL7 and older)
      when: yum_log_status.stat.exists | default(false)
      shell: |
        grep "Upgraded" /var/log/yum.log* | tail -n 1 | awk '{print $1, $2, $3}'
      register: last_patch_yum
      changed_when: false
      failed_when: false

    - name: Get the last patch date from dnf logs (for OL8 and newer)
      when: dnf_log_status.stat.exists | default(false)
      shell: |
        grep "Upgraded" /var/log/dnf.log* | tail -n 1 | awk '{print $1, $2, $3}'
      register: last_patch_dnf
      changed_when: false
      failed_when: false

    - name: Set the last patch info for OL7 and older (yum)
      when: yum_log_status.stat.exists | default(false)
      set_fact:
        last_patch_info: "{{ inventory_hostname }} - Last patch (via yum log): {{ last_patch_yum.stdout }}"

    - name: Set the last patch info for OL8 and newer (dnf)
      when: dnf_log_status.stat.exists | default(false)
      set_fact:
        last_patch_info: "{{ inventory_hostname }} - Last patch (via dnf log): {{ last_patch_dnf.stdout }}"

    - name: Debug the last patch info
      debug:
        msg: "Last patch info: {{ last_patch_info }}"

    - name: Append last patch info to a file on the Ansible control machine
      delegate_to: localhost
      ansible.builtin.lineinfile:
        path: "/home/{{ ansible_user }}/oracle_last_patched_report.txt"
        line: "{{ last_patch_info }}"
        create: yes
        mode: '0644'

    - name: Verify the file is updated on the control machine
      delegate_to: localhost
      stat:
        path: "/home/{{ ansible_user }}/oracle_last_patched_report.txt"
      register: file_stat

    - name: Debug file status
      delegate_to: localhost
      debug:
        msg: "File status: {{ file_stat }}"
