---
- name: Create a user on a Linux system
  hosts: all
  become: true 
  vars:
    username: ansible
  tasks:
    - name: Create user 
      user:
        name: "{{ username }}"
        state: present  
        shell: /bin/bash 
        comment: "Ansible Automation"

    - name: add users key
      authorized_key:
        user: ansible
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDNV/EmyAjEhjYqzXd77OXeBh0MvkD1cWZ0fkgpxe//PyW4IOrg0mSzTacsRxc7NXzgngyu2x8gc8G5xX4OYwvpaRlBWsuLYizzF/wqidq9oQPCd2i7zDvPTHpIb5M4rT8JK12ENkmwKgNDVbgP9CWV42mWzGGEMoJwZry+2EAkiiqE0n7AUOcaBnDHcNonCyyHhKembBYO5m/r6KSOAQOY1/fTaNe/sSCOxF9O6P4js3iO6W0faib+sY213ZdC9lpLDh/P/8wux6bDD/qRX2a805ujLuppINJsX3/1YqqeCB6J/j2+izS0Cn+VlVh+OlccAViRpv7sgqBaQsKxoKeBI8OrJeMlDgumtdEQtp7QTnOOaGk4wJR+m0F2L+gfXJ2ZnyQHJu0k5xvFX922w8pXo4TCrSlcqvL68nnuFpfzYFr9ei/YOotdWXDbDuAs9A48yCJ2mr6b0MJT6B+PplcASpl1phb7r2bXhl9er0wDGenoaOjv3iJYH9TLE8CmojM= root@dcpolautom01"
        manage_dir: True
        path: "/home/ansible/.ssh/authorized_keys"
        state: present
