---
- name: Create a user on a Linux system
  hosts: all
  become: true 
  vars:
    username: ansible
  tasks:
    - name: Create user 
      user:
        name: "{{ username }}"
        state: present  
        shell: /bin/bash 
        comment: "Ansible Automation"
