---

- hosts: all
  become: yes
  become_user: root
  gather_facts: no
  tasks:
  - name: Disable all repos
    command: dnf --disablerepo="*"
    
  - name: Enable ol8_appstream & baseos_latest Repos 
    dnf:
      enablerepo: "{{ item }}"
    loop:
      - ol8_appstream
      - ol8_baseos_latest
      
  - name: Enable all repos
    command: dnf --enablerepo="*"
