---

- hosts: all
  become: yes
  become_user: root
  gather_facts: no
  tasks:
  - name: Enable ol8_appstream Repos 
    dnf:
      enablerepo: ol8_appstream
  - name: Enable ol8_baseos_latest Repos 
    dnf:
      enablerepo: ol8_baseos_latest
