---
- hosts: all
  become: yes
  become_user: root
  gather_facts: no
  pre_tasks:
    - include: vars.yaml
  tasks:
  - name: vmware
    vmware_guest_snapshot:
      state: present 
      name:  "{{ inventory_hostname }} "
      snapshot_name: "{{ inventory_hostname }}.backup"
      description: "Ansible Managed Snapshot"
      memory_dump: False 
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: "{{ vcenter_certs }}"
      port: 443
