- name: Enable all repos
  shell: |
    dnf config-manager --enable ol*     

- name: add sudoers file
  copy:
    src: files/ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440
